const UserGeneralData = [
    {
        id: 1,
        userId:"123456",
        SiteTitle:'MERN Stack',
        tagLine:'MERN stack is a JavaScript stack that’s designed to make the development process smoother. MERN includes four open-source components: MongoDB, Express, React, and Node.js. These components provide an end-to-end framework for developers to work in.',
        theme:'Light',
        PreferdLanguagesId:[1,2,4,6],
        timeZone:'GMT+5:30',
    },
    {
        id: 2,
        userId:'523457',
        SiteTitle:'MEAN Stack',
        tagLine:'MEAN is a free and open-source JavaScript software stack for building dynamic web sites and web applications. The MEAN stack is MongoDB, Express.js, AngularJS (or Angular), and Node.js.',
        theme:'Dark',
        PreferdLanguagesId:[7,2,4,6],
        timeZone:'GMT+1:30',
    },
    {
        id: 3,
        userId:'24657',
        SiteTitle:'MEVN Stack',
        tagLine:'MEVN is a free and open-source JavaScript software stack for building dynamic web sites and web applications. The MEVN stack is MongoDB, Express.js, VueJS, and Node.js.',
        theme:'Dark',
        PreferdLanguagesId:[8,2,4,6],
        timeZone:'GMT-6:30',
    },
    {
        id: 4,
        userId:'84395',
        SiteTitle:'LAMP Stack',
        tagLine:'LAMP is an archetypal model of web service stacks, named as an acronym of the names of its original four open-source components: the Linux operating system, the Apache HTTP Server, the MySQL relational database management system (RDBMS), and the PHP programming language.',
        theme:'Light',
        PreferdLanguagesId:[9,10,11,12],
        timeZone:'GMT+3:30',
    },
    {
        id: 5,
        userId:'96472',
        SiteTitle:'WAMP Stack',
        tagLine:'WAMP is an acronym that stands for Windows, Apache, MySQL, and PHP. It is a variation of LAMP stack that is used for Windows operating systems.',
        theme:'Dark',
        PreferdLanguagesId:[13,10,11,12],
        timeZone:'GMT-1:30',
    },
    {
        id: 6,
        userId: '234567',
        SiteTitle: 'MERN Stack',
        tagLine: 'MERN stack is a JavaScript stack that’s designed to make the development process smoother. MERN includes four open-source components: MongoDB, Express, React, and Node.js. These components provide an end-to-end framework for developers to work in.',
        theme:'Light',
        PreferdLanguagesId:[1,2,4,6],
        timeZone: 'GMT+5:30',
    },
    {
        id: 7,
        userId: '456789',
        SiteTitle: 'MEAN Stack',
        tagLine: 'MEAN is a free and open-source JavaScript software stack for building dynamic web sites and web applications. The MEAN stack is MongoDB, Express.js, AngularJS (or Angular), and Node.js.',
        theme:'Dark',
        PreferdLanguagesId:[7,2,4,6],
        timeZone: 'GMT+1:30',
    },
    {
        id: 8,
        userId: '567890',
        SiteTitle: 'MEVN Stack',
        tagLine: 'MEVN is a free and open-source JavaScript software stack for building dynamic web sites and web applications. The MEVN stack is MongoDB, Express.js, VueJS, and Node.js.',
        theme:'Light',
        PreferdLanguagesId:[8,2,4,6],
        timeZone: 'GMT-6:30',
    },
    {
        id: 9,
        userId: '678901',
        SiteTitle: 'LAMP Stack',
        tagLine: 'LAMP is an archetypal model of web service stacks, named as an acronym of the names of its original four open-source components: the Linux operating system, the Apache HTTP Server, the MySQL relational database management system (RDBMS), and the PHP programming language.',
        theme:'Light',
        PreferdLanguagesId:[9,10,11,12],
        timeZone: 'GMT+3:30',
    },
    {
        id: 10,
        userId: '789012',
        SiteTitle: 'WAMP Stack',
        tagLine: 'WAMP is an acronym that stands for Windows, Apache, MySQL, and PHP. It is a variation of LAMP stack that is used for Windows operating systems.',
        theme:'Light',
        PreferdLanguagesId:[13,10,11,12],
        timeZone: 'GMT-1:30',
    },
    {
        id: 11,
        userId: '890123',
        SiteTitle: 'MERN Stack',
        tagLine: 'MERN stack is a JavaScript stack that’s designed to make the development process smoother. MERN includes four open-source components: MongoDB, Express, React, and Node.js. These components provide an end-to-end framework for developers to work in.',
        theme:'Dark',
        PreferdLanguagesId:[1,2,4,6],
        timeZone: 'GMT+5:30',
    },
    {
        id: 12,
        userId: '901234',
        SiteTitle: 'MEAN Stack',
        tagLine: 'MEAN is a free and open-source JavaScript software stack for building dynamic web sites and web applications. The MEAN stack is MongoDB, Express.js, AngularJS (or Angular), and Node.js.',
        theme:'Light',
        PreferdLanguagesId:[7,2,4,6],
        timeZone: 'GMT+1:30',
    },
    {
        id: 13,
        userId:'012345',
        SiteTitle: 'MEVN Stack',
        tagLine: 'MEVN is a free and open-source JavaScript software stack for building dynamic web sites and web applications. The MEVN stack is MongoDB, Express.js, VueJS, and Node.js.',
        theme:'Dark',
        PreferdLanguagesId:[8,2,4,6],
        timeZone: 'GMT-6:30',
    },
    {
        id: 14,
        userId: '112233',
        SiteTitle: 'LAMP Stack',
        tagLine: 'LAMP is an archetypal model of web service stacks, named as an acronym of the names of its original four open-source components: the Linux operating system, the Apache HTTP Server, the MySQL relational database management system (RDBMS), and the PHP programming language.',
        theme:'Light',
        PreferdLanguagesId:[9,10,11,12],
        timeZone: 'GMT+3:30',
    }
]

export default UserGeneralData;