export const CLIENTS_DETAILS_REQUEST = "CLIENT_DETAILS_REQUEST";
export const CLIENTS_DETAILS_SUCCESS = "CLIENT_DETAILS_SUCCESS";
export const CLIENTS_DETAILS_FAIL = "CLIENT_DETAILS_FAIL";

export const CREATE_CLIENT_REQUEST = "CREATE_CLIENT_REQUEST";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const CREATE_CLIENT_FAIL = "CREATE_CLIENT_FAIL";

export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAIL = "DELETE_CLIENT_FAIL";
export const DELETE_CLIENT_RESET = "DELETE_CLIENT_RESET";
