export const PORTFOLIO_DETAILS_REQUEST = "PORTFOLIO_DETAILS_REQUEST";
export const PORTFOLIO_DETAILS_SUCCESS = "PORTFOLIO_DETAILS_SUCCESS";
export const PORTFOLIO_DETAILS_FAIL = "PORTFOLIO_DETAILS_FAIL";

export const CREATE_PORTFOLIO_REQUEST = "CREATE_PORTFOLIO_REQUEST";
export const CREATE_PORTFOLIO_SUCCESS = "CREATE_PORTFOLIO_SUCCESS";
export const CREATE_PORTFOLIO_FAIL = "CREATE_PORTFOLIO_FAIL";
